main: net.darkscorner.paintball.Main
name: DarkPaintball
version: 1.0
author: TheBirmanator
api-version: 1.14
depend: [ArcadeCoinsAPI]
description: Paintball minigame for DarksCorner
commands:
  join:
   usage: /<command>
   description: Allows a player to join a game
  leave:
   usage: /<command>
   description: Allows a player to leave a game
  games:
   usage: /<command>
   description: Opens the main game menu
   aliases: [spec]
  arena:
   usage: /<command>
   description: Allows a player to break blocks
  paint:
   usage: /<command>
   description: View paint colour options
  guns:
   usage: /<command>
   description: View different guns
  viewstats:
   usage: /<command>
   description: View game statistics for a player