main: net.darkscorner.paintball.Main
name: Paintball
version: 1.0
author: TheBirmanator
api-version: 1.15
softdepend:
  - Multiverse-Core
#depend: [ArcadeCoinsAPI]
description: Paintball minigame for DarksCorner
commands:
  paintball:
    usage: /<command>
    aliases: [pb]
    description: Main cmd
  join:
   usage: /<command>
   description: Allows a player to join a game
  leave:
   usage: /<command>
   description: Allows a player to leave a game
  games:
   usage: /<command>
   description: Opens the main game menu
   aliases: [spec]
  arena:
   usage: /<command>
   description: Allows a player to break blocks
  paint:
   usage: /<command>
   description: View paint colour options
  guns:
   usage: /<command>
   description: View different guns
  viewstats:
   usage: /<command>
   description: View game statistics for a player